resources:
  Resources:
    # We use two different tables, so we can have a better access control
    # Prevent replays L1 -> L2
    EthereumTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        TableName: ${self:custom.resourcePrefix}Ethereum
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PrimaryKey
            AttributeType: S
        KeySchema:
          - AttributeName: PrimaryKey
            KeyType: HASH

    # Prevent replays L2 -> L1, allows tx lookup by message key
    StarknetTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        TableName: ${self:custom.resourcePrefix}Starknet
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PrimaryKey
            AttributeType: S
        KeySchema:
          - AttributeName: PrimaryKey
            KeyType: HASH