functions:
  ReceiveMessage:
    timeout: 10
    memorySize: 128
    handler: src/functions/ethereum/blockNative.main
    environment:
      QUEUE_URL: !Ref EthereumTxQueue
    events:
      - http:
          method: POST
          path: /hook
    # allow sending messages to EthereumTxQueue
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
            - 'sqs:SendMessage'
        Resource:
          - !GetAtt
            - EthereumTxQueue
            - Arn

  StoreMessage:
    timeout: 120
    memorySize: 128
    handler: src/functions/ethereum/store.main
    reservedConcurrency: 1
    environment:
      ETHEREUM_TABLE_NAME: !Ref EthereumTable
      ETHEREUM_PROVIDER_URL: ${ssm:${self:custom.resourcePrefix}EthereumProviderUrl~true}
      ETHEREUM_CONTRACT: ${ssm:${self:custom.resourcePrefix}EthereumContract}
      IC_PRIVATE_KEY: ${ssm:${self:custom.resourcePrefix}ICPrivateKey~true}
      IC_CANISTER_ID: ${ssm:${self:custom.resourcePrefix}ICCanisterId}
      QUEUE_URL: !Ref EthereumTxQueue
    events:
      - sqs:
          batchSize: 10
          arn:
            Fn::GetAtt:
              - EthereumTxQueue
              - Arn
    iamRoleStatements:
      # allow removing processed messages from queue
      - Effect: 'Allow'
        Action:
            - 'sqs:DeleteMessageBatch'
        Resource:
          - !GetAtt
            - EthereumTxQueue
            - Arn
      - Effect: 'Allow'
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource: 
          - !GetAtt 
            - EthereumTable  
            - Arn

resources:
  Resources:
    EthereumTxQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.resourcePrefix}EthereumTxQueue.fifo
        ContentBasedDeduplication: true
        FifoQueue: true
        VisibilityTimeout: 300 # 5 minutes
        RedrivePolicy:
          maxReceiveCount: 3
          deadLetterTargetArn: !GetAtt
            - EthereumTxDLQ
            - Arn
    EthereumTxDLQ:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: ${self:custom.resourcePrefix}EthereumTxDLQ.fifo
        MessageRetentionPeriod: 1209600 # 14 days