service: ledger

provider:
  name: aws
  profile: ledger
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    DEBUG: "*"
    AWS_STAGE: ${self:provider.stage}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

custom:
  stagePrefix:
    dev: LedgerTestnet
    prd: LedgerMainnet
    local: LedgerLocal

  resourcePrefix: ${self:custom.stagePrefix.${self:provider.stage}}

  # stack termination protection
  serverlessTerminationProtection:
    stages:
      - prd
      - dev
  domain:
    dev: ledger-dev.psychedelic.ooo
    prd: ledger.psychedelic.ooo

  # ToDo {botch} confirm domains
  # customDomain:
  #   domainName: ${self:custom.domain.${opt:stage, 'dev'}}
  #   stage: ${self:provider.stage}
  #   basePath: ''
  #   autoDomain: true
  #   certificateName: '*.psychedelic.ooo'
  #   createRoute53Record: false
  serverless-offline-sns:
  port: 4002
  debug: false
  sns-endpoint: http://127.0.0.1:4002
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
  serverless-iam-roles-per-function:
    defaultInherit: true # Each function will inherit the service level roles too.
  prune:
    automatic: true
    number: 3
  serverless-offline:
    httpPort: 3000
    stageVariables:
      ethereum_provider_url: ${env:ETHEREUM_PROVIDER_URL}
      canister_id: ${env:CANISTER_ID}
      queue_url: ${env:QUEUE_URL}
      ethereum_contract: ${env:ETHEREUM_CONTRACT}
      kms_key_id: ${env:KMS_KEY_ID}
      kms_key_key: ${env:KMS_PUBLIC_KEY}
      stage: ${env:STAGE}
      aws_stage: ${env:AWS_STAGE}

plugins:
  - serverless-webpack
  - serverless-stack-termination-protection
  - serverless-iam-roles-per-function
  - serverless-prune-plugin
  - serverless-offline-sns
  - serverless-offline
  - serverless-dotenv-plugin

package:
  individually: true

functions:
  #
  # L1 -> L2 messages, capture transactions from Ethereum
  #
  ReceiveMessage:
    timeout: 10
    memorySize: 128
    handler: src/functions/ethereum/blockNative.main
    environment:
      QUEUE_URL: !Ref EthereumTxWithdrawQueue
    events:
      - http:
          method: POST
          path: /hook
          request:
            schema:
              application/json: ${file(src/functions/ethereum/schema_json.json)}
    # allow sending messages to EthereumTxWithdrawQueue
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "sqs:SendMessage"
        Resource:
          - !GetAtt
            - EthereumTxWithdrawQueue
            - Arn
  # ! do not rename !
  RemoveClaimable:
    timeout: 120
    memorySize: 128
    handler: src/functions/ethereum/remove.main
    reservedConcurrency: 1
    environment:
      # Ethereum Provider API URL (only for querying L1 state)
      ETHEREUM_PROVIDER_URL: ${ssm:${self:custom.resourcePrefix}EthereumProviderUrl}
      # ETHEREUM_PROVIDER_URL: ${ssm:${self:custom.resourcePrefix}EthereumProviderUrl~true}
      # AWS KMS Key ID, IC Operator
      # KMS_KEY_ID: !Ref InternetComputerOperator
      # AWS KMS Public Key (base64 encoded), IC Operator
      KMS_PUBLIC_KEY: ${ssm:${self:custom.resourcePrefix}KMSPublicKeyIC}
      # Terabethia L1 Contract ID
      # EthProxy Canister ID
      ETH_PROXY_CANISTER_ID: ${ssm:${self:custom.resourcePrefix}EthProxyCanisterId}
      QUEUE_URL: !Ref EthereumTxWithdrawQueue
    events:
      - sqs:
          arn: !GetAtt
            - EthereumTxWithdrawQueue
            - Arn
          batchSize: 10
    iamRoleStatements:
      # allow removing processed messages from queue
      - Effect: "Allow"
        Action:
          - "sqs:DeleteMessage"
        Resource:
          - !GetAtt
            - EthereumTxWithdrawQueue
            - Arn
resources:
  Resources:
    #
    # SQS
    #
    EthereumTxWithdrawQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.resourcePrefix}EthereumTxWithdrawQueue.fifo
        ContentBasedDeduplication: true
        FifoQueue: true
        DelaySeconds: 30
        VisibilityTimeout: 300 # 5 minutes
        RedrivePolicy:
          maxReceiveCount: 3
          deadLetterTargetArn: !GetAtt
            - EthereumTxWithdrawDLQ
            - Arn
    EthereumTxWithdrawDLQ:
      Type: AWS::SQS::Queue
      Properties:
        FifoQueue: true
        QueueName: ${self:custom.resourcePrefix}EthereumTxWithdrawDLQ.fifo
        MessageRetentionPeriod: 1209600 # 14 days
