[workspace]
members = [
    "src/dip20_proxy",
    "src/magic_bridge",
    "src/dip721_proxy",
]
exclude = [
    "DIP20/rust",
    "DIP721/nft-v2"
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1